version: '3.7'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
  
  front:
    image: killraoux/mon-app:latest
    ports:
      - "80:80"
    environment:
      - API_URL=http://localhost:8080/api
  
  backend:
    image: killraoux/demo-backend:v1.2.0
    ports:
      - "8080:8080"